### ISSUE TITLE
Find out what causes the delay for the keyboard input

### ISSUE THREAD

**Issue by Humblean** [Herkulisch/Chip-8#3]
Some Keys just do not get recognized or get recognized to late. I have to find out why this is the case.

**Comment by tobiasvl** [comment]
Are you using raw mode? https://docs.rs/crossterm/0.21.0/crossterm/terminal/#raw-mode

**Comment by Humblean** [comment]
No I was not, I changed it to see if it fixes the issue. But the issue stays the same

**Comment by Humblean** [comment]
Turns out I misunderstood the documentation for the the Ex9E Instruction. So thats why the keys never got recognized. Now I only have to get the correct timing to have some fluent controls.
